if: branch != feature/appveyor-ci
language: cpp
os:
- linux
- osx
env:
  global:
  - ARDUINO_SDK_BASE_PATH=arduino-sdk/arduino
  matrix:
  - ARDUINO_SDK_VERSION=1.6.10
  - ARDUINO_SDK_VERSION=1.8.7
cache:
  directories:
  - $HOME/$ARDUINO_SDK_BASE_PATH-$ARDUINO_SDK_VERSION
addons:
  apt:
    packages:
    - binutils-avr
    - avr-libc
    - avrdude
    - cmake
before_install:
- sdk_path="$HOME/$ARDUINO_SDK_BASE_PATH-$ARDUINO_SDK_VERSION"
- mkdir -p "$sdk_path"
- cd "$sdk_path/../.." # Get one level above 'arduino-sdk'
- |
  if [[ $TRAVIS_OS_NAME == linux ]]; then
    sdk_file="arduino-$ARDUINO_SDK_VERSION-linux64.tar.xz"
  else
    sdk_file="arduino-$ARDUINO_SDK_VERSION-macosx.zip"
  fi
- wget "https://downloads.arduino.cc/$sdk_file" -O "$sdk_file"
- |
  if [[ $TRAVIS_OS_NAME == linux ]]; then
    tar xf "$sdk_file" -C arduino-sdk
  else
    unzip "$sdk_file" -d arduino-sdk
  fi
- ls -l "$sdk_path"
- ls -l "$sdk_path/.."
- export ARDUINO_SDK_PATH="$sdk_path"
install:
- cd "$TRAVIS_BUILD_DIR"
- mkdir build
- rm -rf build/*
- cd build/
script:
- cmake -D CMAKE_TOOLCHAIN_FILE="../cmake/Arduino-Toolchain.cmake" ../examples
- make
after_failure:
- cat CMakeFiles/CMakeOutput.log
