version: '{build}'
image: Visual Studio 2017
environment:
  MINGW_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  matrix:
#  - ARDUINO_SDK_VERSION: 1.6.13
  - ARDUINO_SDK_VERSION: 1.8.6
install:
- ps: cinst unzip
- ps: $env:ARDUINO_SDK_FILE = "arduino-$env:ARDUINO_SDK_VERSION-windows.zip"
- ps: $env:ARDUINO_SDK_URI = "https://downloads.arduino.cc/$env:ARDUINO_SDK_FILE"
- ps: wget "$env:ARDUINO_SDK_URI" -O "$env:ARDUINO_SDK_FILE"
- ps: unzip "$env:ARDUINO_SDK_FILE" -d "arduino-sdk"
- ps: $env:ARDUINO_SDK_PATH = "$pwd\arduino-sdk\arduino-$env:ARDUINO_SDK_VERSION"
# FIXME: Windows path separators (\) need to be changed to "/" for cmake to properly handle it
- ps: $env:ARDUINO_SDK_PATH = ($env:ARDUINO_SDK_PATH -replace "\\","/")
before_build:
- ps: Copy-Item -Path $env:MINGW_PATH\mingw32-make.exe -Destination $env:MINGW_PATH\make.exe
build_script:
# Add the MinGW Path to the system PATH temporarily for this session
- ps: $env:Path += ";$env:MINGW_PATH"
- ps: mkdir build
- ps: cd build
- ps: echo "$env:ARDUINO_SDK_PATH"
- ps: >-
    cmake -G "MinGW Makefiles"
    -D CMAKE_TOOLCHAIN_FILE="..\cmake\Arduino-Toolchain.cmake"
    -D CMAKE_SH="CMAKE_SH-NOTFOUND"
    --no-warn-unused-cli
    ..\examples
- ps: make.exe
after_build:
- 7z a arduino-cmake-ng.zip %APPVEYOR_BUILD_FOLDER%\cmake
artifacts:
- path: arduino-cmake-ng.zip
  name: Arduino-CMake-NG
deploy:
- provider: GitHub
  description: 'ToDo'
  artifact: arduino-cmake-ng.zip
  auth_token:
    secure: nTRyL3xmSCBVKQPd1wf/VoUSRIATFVSSCSlKm52esfQ=
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
on_failure:
- ps: cat CMakeFiles/CMakeOutput.log
